# SQL SERVER
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databasename=Eventos
<<<<<<< HEAD
    username: userpelaez
    password: 123
=======
    username: XXX
    password: XXXXX
>>>>>>> Evento Catering v2.0
  jpa:
    database: sql-server
    hibernate:
      ddl-auto: update
    show-sql: false
  
server:
  port: 8081